services:
  backend:
    build: .
    container_name: django_backend
    env_file:
      - backend/.env
    expose:
      - "8000"
    volumes:
      - .:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    expose:
      - "3000"
    environment:
      - PORT=3000
      - VITE_API_URL=/api

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./questions/media:/data/media:ro
