services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sbf-theorie_backend
    env_file:
      - backend/.env
    expose:
      - "8000"
    volumes:
      - ./backend:/app
      - ./questions/questions.json:/app/questions.json:ro
      - sbf-theorie:/app/data
      - sbf-theorie:/app/static_root

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sbf-theorie_frontend
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    container_name: sbf-theorie_proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./questions/media:/data/media:ro

volumes:
  sbf-theorie:
