# Generated by Django 5.2.3 on 2025-06-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('license', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=255, verbose_name='correct answer')),
                ('option2', models.CharField(max_length=255, verbose_name='wrong answer')),
                ('option3', models.CharField(max_length=255, verbose_name='wrong answer')),
                ('option4', models.CharField(max_length=255, verbose_name='wrong answer')),
                ('image', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
